"""empty message

Revision ID: 9a4ce8dd0be0
Revises: e8e9f5e3d844
Create Date: 2022-05-02 16:39:11.619350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4ce8dd0be0'
down_revision = 'e8e9f5e3d844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mass', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hair_color', sa.String(length=80), nullable=True),
    sa.Column('skin_color', sa.String(length=80), nullable=True),
    sa.Column('eye_color', sa.String(length=80), nullable=True),
    sa.Column('birth_year', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('homeworld', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.String(length=80), nullable=True),
    sa.Column('rotation_period', sa.String(length=80), nullable=True),
    sa.Column('orbital_period', sa.String(length=80), nullable=True),
    sa.Column('gravity', sa.String(length=80), nullable=True),
    sa.Column('climate', sa.String(length=80), nullable=True),
    sa.Column('terrain', sa.String(length=80), nullable=True),
    sa.Column('surface_water', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('vehicle_class', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=80), nullable=True),
    sa.Column('lenght', sa.String(length=80), nullable=True),
    sa.Column('crew', sa.String(length=80), nullable=True),
    sa.Column('passengers', sa.String(length=80), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=80), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=80), nullable=True),
    sa.Column('consumables', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'description')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('character')
    op.drop_table('item')
    # ### end Alembic commands ###
